### ISSUE TITLE
Failed to activate the fixmyjs package

### ISSUE THREAD

**Issue by felipebhz** [sindresorhus/atom-fixmyjs#9] opened 2015-04-01 20:36 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [fixmyjs](https://github.com/sindresorhus/atom-fixmyjs) package, v1.3.0

### Stack Trace

Failed to activate the fixmyjs package

```
At Cannot find module 'fixmyjs'

Error: Cannot find module 'fixmyjs'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/felipebhz/.atom/packages/fixmyjs/index.js:2:15)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:741:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:223:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  5x -0:30.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 FixMyJS (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.7.1
editor-stats, v0.17.0
fixmyjs, v1.3.0
linter, v0.12.0
linter-jshint, v0.1.0

# Dev
No dev packages
```

**Comment by sindresorhus** [comment] 2015-04-02 16:33
Duplicate of https://github.com/sindresorhus/atom-fixmyjs/issues/7

**Closed by sindresorhus** 2015-04-02 16:33 UTC

**Comment by jdheeter** [comment] 2016-01-18 23:34
What's the solution?

**Comment by evildevil666** [comment] 2016-03-16 12:45
As mentioned by @sindresorhus in #7, `npm install` in `~/.atom/packages/fixmyjs` works

**Comment by rakibulalam** [comment] 2017-03-15 09:04
go to : cd ~/.atom/packages/fixmyjs 
and run it by manualy : npm install
